## Course Information
INFO 521: Introduction to Machine Learning\
Instructor: Xuan Lu, College of Information Science

## Instructions
#### Objectives
This worksheet will assess your knowledge of basic commands in Python. Please review the lectures, suggested readings, and additional resources before starting the homework, as this document closely follows the provided materials.

#### Grading
Please note that grades are **NOT exclusively based on your final answers**. We will be grading the overall structure and logic of your code. Feel free to use as many lines as you need to answer each of the questions. I also highly recommend and strongly encourage adding comments (`#`) to your code. Comments will certainly improve the reproducibility and readability of your submission. Commenting your code is also good coding practice. **Specifically for the course, you’ll get better feedback if the TA is able to understand your code in detail.**

#### Submission
This homework is due by the end of the week it is released (**Sunday, 11:59 pm AZ time**). Please contact the instructor if you are (i) having issues opening the assignment, (ii) not understanding the questions, or (iii) having issues submitting your assignment. Note that late submissions are subject to a penalty (see late work policies in the syllabus).
- Please submit a single Jupyter Notebook file (this file). Answers to each question should be included in the relevant block of code (see below). Rename your file to "**lastname_Hw1.ipynb**" before submitting. If a given block of code is causing issues and you didn't manage to fix it, please add comments.

#### Time commitment
Please reach out if you’re taking more than ~18h to complete (1) this homework, (2) reading the book chapters, and (3) going over the lectures. I will be happy to provide accommodations if necessary. **Do not wait until the last minute to start working on this homework**. In most cases, working under pressure will certainly increase the time needed to answer each of these questions and the instructor and the TA might not be 100% available on Sundays to troubleshoot with you.

#### Looking for help?
First, please go over the relevant readings for this week. Second, if you’re still struggling with any of the questions, do some independent research (e.g. stackoverflow is a wonderful resource). Don’t forget that your classmates will also be working on the same questions - reach out for help (check under the Discussion forum for folks looking to interact with other students in this class or start your own thread). Finally, the TA is available to answer any questions during office hours and via email.

## Questions

Name: [Gayathri Renganathan]\
Affiliation: [iSchool]

#### Question 1

Assign the value 26 to a variable *x*.
Create a list *y* with the values '[2, 36, 1, 98, 124]'.
Multiply the value of *x* with each element of *y* element-wise and save the result in a new list *z*.
Calculate the sum of all elements in *z* and save the result in a new variable named *Q1*.

In [ ]:
pip i

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [18]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 5.7 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.5 MB 3.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.5 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/11.5 MB 4.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.5 MB 4.3 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.5 MB 4.1 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.5 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.5 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.1/11.5 MB 3.9 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.5 MB 4.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.5 MB 4.1 MB/s eta 0:00:01
   --

In [3]:
# BEGIN SOLUTION
import numpy as np

#Assigning scalar value to a variable
x = 26

np.

#Creating a array
y = np.array([2,36, 1,98, 124])

#Multiply x with each element of y
z= x*y

#Sum of all elements in z
Q1 = np.sum(z)
# END SOLUTION

#### Question 2

Generate a sequence from 21 to 400 and save it in a variable named *Q2_1*.
Generate a second sequence from 2 to -35 and save it in a variable named *Q2_2*.


In [4]:
# BEGIN SOLUTION
#Generate a sequence from 21 to 400
Q2_1 = np.arange(21,401)

#Generate a sequence from 2 to -35
Q2_2 = np.arange(2, -36, -1)
Q2_2
# END SOLUTION

array([  2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10,
       -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23,
       -24, -25, -26, -27, -28, -29, -30, -31, -32, -33, -34, -35])

#### Question 3

Generate a sequence from -3 to 9 with steps of 0.1 and save it in a variable named *Q3*.

In [5]:
# BEGIN SOLUTION
Q3 = np.linspace(-3,9, 121)
Q3

# END SOLUTION

array([-3. , -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. ,
       -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9,
       -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,
        0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,
        1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,
        2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,
        3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,
        4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,
        5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,
        6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,
        8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ])

#### Question 4
Randomly sample 100 times from a total of 20 elements of *Q3* (with replacement).
Save the results in a new variable named *Q4* as a list.

In [6]:
# BEGIN SOLUTION
Q4 = []
for i in range(100):
    Q4.append(np.random.choice(Q3, 20, replace = True))
Q4
# END SOLUTION

[array([ 8.7,  2.5, -2. ,  4.5,  6.4,  2.8,  4.7,  2.8,  6.4, -0.9,  4.2,
         1.6,  5. , -2.2, -2.7,  6.1,  8.7,  5.9, -1.5, -2. ]),
 array([ 0.3,  3.4,  6.7, -2.5,  6.2,  3.7,  3.6,  1. ,  8.3,  2.3,  0.3,
         5.9,  0.2,  2.3,  6. ,  5.5,  2.1,  8.4,  8.5,  7.6]),
 array([ 6.1,  6.5,  5.4,  6.4, -2.7,  1.7,  3.6,  4.9,  1.1,  7.3,  1.3,
         6.9,  2.6,  1.4,  7. , -1.6,  2. ,  0.5, -1.8, -2.3]),
 array([-1.2,  2.7, -0.3,  0.8,  6.9,  1.9,  7. , -1.7, -0.9,  7.5,  3. ,
         2.1, -0.7, -1.3, -2. , -2.7,  0.6,  3.2,  6.4,  2.7]),
 array([-0.3, -0.1,  2.7,  1.1,  0.7,  2. ,  4.7,  4.7,  7.1,  8.4,  5.4,
         8.6,  8.1,  4.4, -0.9,  1. ,  6.1,  0. ,  2.7, -2. ]),
 array([-1.1, -1.8,  2.3,  2.5,  0. ,  6.8,  1.8,  8. ,  8.8,  4.4,  4.8,
         1.8,  7.6, -0.9,  6.6,  4.5,  4.1,  3.6,  2.2,  3.7]),
 array([-0.4,  2.2,  0.2,  0.6,  2. ,  6.8,  0.3,  8.9,  7. ,  6.8,  1.6,
         8. ,  0.3,  8.4, -2.2,  4.4,  6.1,  1. ,  4.2,  7. ]),
 array([ 4.2,  2.9,  6.2,  6.7,  2

#### Question 5
Define two lists: one named *t* with the strings ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'] and another named m with the values [90, 80, 50, 20, 5, 20].
Combine these lists column-wise into a DataFrame with 6 rows and 2 columns.
Save this DataFrame in a new variable named *Q5*.

In [7]:
# BEGIN SOLUTION
import pandas as pd

t = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat']
m = [90, 80, 50, 20, 5, 20]

#Combining list column-wise to dataframe 
Q5 = pd.DataFrame(list(zip(t,m)),
               columns =['t', 'm'])

# END SOLUTION

#### Question 6
Create three vectors of length 100:
- *weight* with a mean of 81 and standard deviation of 0.26, in kilograms;
- *height* with a mean of 1.76 and standard deviation of 0.22, in meters;
- *age* with a mean of 25 and standard deviation of 5, in years. Generate these vectors by sampling from normal distributions.\

Create a fourth vector *gender* with the same length as height, randomly sampling (with replacement) from the vector ["A", "B", "C"].

In [46]:
# BEGIN SOLUTION
#Create Vector weight, height, age and gender
weight = np.random.normal(81, 0.26, 100)
height = np.random.normal(1.76, 0.22, 100)
age = np.random.normal(25, 5, 100)
gender = np.random.choice( ["A", "B", "C"], len(height), replace = True)
# END SOLUTION

#### Question 7
Create a DataFrame by combining the four vectors (*weight*, *height*, *age*, and *gender*) as columns.
Add a new column named *BMI* with NaN values.
Save this DataFrame in a new variable named *Q7*.

In [30]:
# BEGIN SOLUTION
#Create Dataframe from vectors and add new Column 'BMI"
Q7 = pd.DataFrame({'weight': weight, 'height': height, 'age':age, 'gender':gender, 'BMI': 'NaN'})

# END SOLUTION

weight    height        age gender  BMI
0   81.241346  1.884208  23.969713      A  NaN
1   80.706914  1.663823  28.886831      A  NaN
2   80.991055  2.203916  30.021091      B  NaN
3   80.703979  1.700897  22.096360      C  NaN
4   81.240744  1.649872  32.350462      C  NaN
..        ...       ...        ...    ...  ...
95  81.409929  1.730249  22.976426      A  NaN
96  81.092184  1.924676  23.035277      A  NaN
97  80.775184  1.838150  25.772255      B  NaN
98  81.210881  1.735242  20.470485      C  NaN
99  81.170974  1.818907  27.544067      C  NaN

[100 rows x 5 columns]

#### Question 8
Generate a new column named *AgeGroup* in the DataFrame *Q7*. 
- The values in this column should be *True* if the age is out of range (i.e., less than 20 or greater than 30), and *False* otherwise.

Save the updated DataFrame in a new variable named *Q8*.

In [31]:
# BEGIN SOLUTION
#Create new column AgeGroup
Q7['AgeGroup'] = np.where((Q7['age'] < 20) | (Q7['age'] > 30), True, False)
Q8 = pd.DataFrame(Q7)
# END SOLUTION

#### Question 9
Calculate the Body Mass Index (BMI) for all people in the *Q8* DataFrame using the formula:
$$BMI = \frac{Weight_{(Kg)}} {Height_{(m)}^2}$$
Store the calculated BMI values in the *BMI* column of *Q8*.
Save the updated DataFrame in a new variable named *Q9*.

In [33]:
# BEGIN SOLUTION
#update BMI column using the formula
BMI = Q8['weight'] / (Q8['height'] ** 2)
Q8['BMI'] = BMI
Q9 = pd.DataFrame(Q8)

# END SOLUTION

weight    height        age gender        BMI  AgeGroup
0   81.241346  1.884208  23.969713      A  22.883337     False
1   80.706914  1.663823  28.886831      A  29.153900     False
2   80.991055  2.203916  30.021091      B  16.674283      True
3   80.703979  1.700897  22.096360      C  27.895798     False
4   81.240744  1.649872  32.350462      C  29.845133      True
..        ...       ...        ...    ...        ...       ...
95  81.409929  1.730249  22.976426      A  27.193183     False
96  81.092184  1.924676  23.035277      A  21.890907     False
97  80.775184  1.838150  25.772255      B  23.906510     False
98  81.210881  1.735242  20.470485      C  26.970817     False
99  81.170974  1.818907  27.544067      C  24.534643     False

[100 rows x 6 columns]

#### Question 10
Create a function named *function_Q10* that calculates the BMI. The function should take two arguments, height and weight, and return a numerical vector of BMI values.\
Test the function by applying it to the *height* and *weight* columns from the *Q9* DataFrame and show that it works.

In [35]:
# BEGIN SOLUTION
#Function to calculate BMI
def function_Q10(height, weight):
  return weight / (height ** 2)

#new BMI calculated using the function
new_BMI =  Q9.apply(lambda x: function_Q10(x['height'], x['weight']), axis=1)

#Check if the new BMI is same as old one
result = [a == b for a, b in zip(new_BMI, Q9['BMI'])]
print(all(result))
# END SOLUTION

True


#### Question 11
Create a function named *function_Q11* that calculates the mean BMI for a specific gender. The function should take two arguments:
- A DataFrame that contains at least the BMI and Gender columns.
- A target gender to calculate the mean BMI for.

Test the function by running it with a specific gender (e.g., 'A') to show that it calculates the mean BMI correctly.

In [36]:
# BEGIN SOLUTION
#Calculate mean BMI for a specified Gender
def function_Q11(data, gender):
  return data[(data['gender'] == gender)]["BMI"].mean()

# Mean BMI for Gender 'A'
print(function_Q11(Q9,'A'))
# END SOLUTION

29.418712578671737


#### Question 12
Append a new column named *BMIc* to the *Q9* DataFrame that adjusts the BMI values based on the *AgeGroup* column.
Specifically:
- If a participant's age falls into the *out of range* category in the *AgeGroup* column, increase their BMI by 10%.
- If not, use the original BMI value.

Save the updated DataFrame as *Q12*.

In [39]:
# BEGIN SOLUTION
#Create new column BMIc
Q9['BMIc'] = np.where(Q9['AgeGroup'] == True, Q9['BMI'] + (Q9['BMI'] * 0.1), Q9['BMI'])
Q12 = pd.DataFrame(Q9)
# END SOLUTION